#!/usr/bin/env ruby

tests = Dir['spec/**/*_spec.rb']
        .sort
        .shuffle(random: Random.new(ENV['GITHUB_SHA'].to_i(16)))
        .select
        .with_index do |_el, i|
          i % ENV['CI_NODE_TOTAL'].to_i == ENV['CI_NODE_INDEX'].to_i
        end

exec "bundle exec rspec #{tests.join(' ')}"
