extends:
  - airbnb
env:
  browser: true
  es6: true
  jquery: true
parser: babel-eslint
rules:
  semi: 0
  no-underscore-dangle: 0
plugins:
  - jest
settings:
  import/resolver:
    node:  { paths: [app/javascript] }
