AllCops:
  DisplayCopNames: true
  Exclude:
    - "app/javascript/**/*"
    - "bin/*"
    - "db/migrate/*"
    - "db/schema.rb"
    - "log/*"
    - "node_modules/**/*"
    - "public/**/*"
    - "vendor/**/*"

Layout/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
