AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - "app/javascript/**/*"
    - "bin/*"
    - "db/migrate/*"
    - "db/schema.rb"
    - "log/*"
    - "node_modules/**/*"
    - "public/**/*"
    - "vendor/**/*"
