version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql_8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - TZ=Asia/Tokyo
  redis:
    image: redis:6
    container_name: redis_6
    ports:
      - "6379:6379"